server:
  port: 8085

spring:
  application:
    name: aggregator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

# ==============================
# Resilience4j Circuit Breaker
# ==============================

resilience4j:
  circuitbreaker:
    instances:

      productCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      inventoryCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      orderCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

# ==============================
# Actuator (optional but useful)
# ==============================

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

  endpoint:
    health:
      show-details: always
