server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
